### PR TITLE
fixed to_toml() dumping

### PR DESCRIPTION
**Pull request by next-franciscoalgaba**
See [Issue 53](https://github.com/fabiocaccamo/python-benedict/issues/53) for more information.

### CODE REVIEW

**Review by fabiocaccamo — CHANGES_REQUESTED** [review]
I don't merge PR without tests, could you provide also a failing test case please?

**Comment by next-franciscoalgaba** [comment]
> I don't merge PR without tests, could you provide also a failing test case please?

Just submitted failing and success tests :)

**Comment by fabiocaccamo** [comment]
@next-franciscoalgaba sorry if I have not merged your PR, but the problem affected all encoders, so is has been faster to fix the problem by myself.

**Comment by fabiocaccamo** [comment]
You can upgrade to `0.24.0` version.

**Pull request closed without merging**
